[workspace]
members = [
    "iocuddle",
    "iocuddle-sgx",

    "sgx-show",
    "sgx-types",
    "sgx-crypto",
    "sgx-traits",
]

[patch.crates-io]
openssl = { git = 'https://github.com/npmccallum/rust-openssl', branch='patch' }
